// Define types for our data structure
type DadosItem = Record<string, string | number>;

interface DadosCategory {
  [key: string]: DadosItem;
}

interface DadosStructure {
  despesa: DadosCategory;
  receita: DadosCategory;
  projetos: DadosCategory;
  tesouraria: DadosCategory;
  [key: string]: DadosCategory; // This allows accessing with dynamic keys
}

export const dados: DadosStructure = {
  despesa: {
    "Fórmula de cálculo": {
      Descrição: "Fórmula de cálculo",
      "Despesas por pagar de períodos anteriores": "(1)",
      "Dotações corrigidas": "(2)",
      "Cativos/Descativos": "(3)",
      Compromissos: "(4)",
      Obrigações: "(5)",
      "Períodos anteriores": "(6)",
      "Período corrente": "(7)",
      Total: "(8)=(6)+(7)",
      "Compromissos a transitar": "(9)=(4)-(5)",
      "Obrigações por pagar": "(10)=(5)-(8)",
      "Períodos anteriores %": "(11)=(6)/(2)x100",
      "Período corrente %": "(12)=(7)/(2)x100",
    },
    "Despesa corrente": {
      Descrição: "Despesa corrente",
      "Despesas por pagar de períodos anteriores": "405.58",
      "Dotações corrigidas": "362574.62",
      "Cativos/Descativos": "0",
      Compromissos: "339931.34",
      Obrigações: "339931.34",
      "Períodos anteriores": "405.58",
      "Período corrente": "337556.21",
      Total: "337961.79",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "1969.55",
      "Períodos anteriores %": "0.11",
      "Período corrente %": "93.1",
    },
    D1: {
      Rubrica: "D1",
      Descrição: "Despesas com o pessoal",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "182599.62",
      "Cativos/Descativos": "0",
      Compromissos: "175450.13",
      Obrigações: "175450.13",
      "Períodos anteriores": "0.0",
      "Período corrente": "174001.41",
      Total: "174001.41",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "1448.72",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "95.29",
    },
    D11: {
      Rubrica: "D11",
      Descrição: "Remunerações Certas e Permanentes",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "144449.62",
      "Cativos/Descativos": "0",
      Compromissos: "141985.26",
      Obrigações: "141985.26",
      "Períodos anteriores": "0.0",
      "Período corrente": "140536.54",
      Total: "140536.54",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "1448.72",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "97.29",
    },
    D12: {
      Rubrica: "D12",
      Descrição: "Abonos Variáveis ou Eventuais",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "2100.0",
      "Cativos/Descativos": "0",
      Compromissos: "1937.51",
      Obrigações: "1937.51",
      "Períodos anteriores": "0.0",
      "Período corrente": "1937.51",
      Total: "1937.51",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "92.26",
    },
    D13: {
      Rubrica: "D13",
      Descrição: "Segurança social",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "36050.0",
      "Cativos/Descativos": "0",
      Compromissos: "31527.36",
      Obrigações: "31527.36",
      "Períodos anteriores": "0.0",
      "Período corrente": "31527.36",
      Total: "31527.36",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "87.45",
    },
    D2: {
      Rubrica: "D2",
      Descrição: "Aquisição de bens e serviços",
      "Despesas por pagar de períodos anteriores": "405.58",
      "Dotações corrigidas": "128180.0",
      "Cativos/Descativos": "0",
      Compromissos: "113996.88",
      Obrigações: "113996.88",
      "Períodos anteriores": "405.58",
      "Período corrente": "113070.47",
      Total: "113476.05",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "520.83",
      "Períodos anteriores %": "0.32",
      "Período corrente %": "88.21",
    },
    D3: {
      Rubrica: "D3",
      Descrição: "Juros e outros encargos",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "15025.0",
      "Cativos/Descativos": "0",
      Compromissos: "14659.95",
      Obrigações: "14659.95",
      "Períodos anteriores": "0.0",
      "Período corrente": "14659.95",
      Total: "14659.95",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "97.57",
    },
    D4: {
      Rubrica: "D4",
      Descrição: "Transferências e subsídios correntes",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "35320.0",
      "Cativos/Descativos": "0",
      Compromissos: "34599.86",
      Obrigações: "34599.86",
      "Períodos anteriores": "0.0",
      "Período corrente": "34599.86",
      Total: "34599.86",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "97.96",
    },
    D41: {
      Rubrica: "D41",
      Descrição: "Transferências correntes",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "35320.0",
      "Cativos/Descativos": "0",
      Compromissos: "34599.86",
      Obrigações: "34599.86",
      "Períodos anteriores": "0.0",
      "Período corrente": "34599.86",
      Total: "34599.86",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "97.96",
    },
    D5: {
      Rubrica: "D5",
      Descrição: "Outras despesas correntes",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "1450.0",
      "Cativos/Descativos": "0",
      Compromissos: "1224.52",
      Obrigações: "1224.52",
      "Períodos anteriores": "0.0",
      "Período corrente": "1224.52",
      Total: "1224.52",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "84.45",
    },
    "Despesa de capital": {
      Descrição: "Despesa de capital",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "72800.0",
      "Cativos/Descativos": "0",
      Compromissos: "67150.66",
      Obrigações: "67150.66",
      "Períodos anteriores": "0.0",
      "Período corrente": "67150.66",
      Total: "67150.66",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "92.24",
    },
    D6: {
      Rubrica: "D6",
      Descrição: "Aquisição de bens de capital",
      "Despesas por pagar de períodos anteriores": "0.0",
      "Dotações corrigidas": "72800.0",
      "Cativos/Descativos": "0",
      Compromissos: "67150.66",
      Obrigações: "67150.66",
      "Períodos anteriores": "0.0",
      "Período corrente": "67150.66",
      Total: "67150.66",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "0.0",
      "Períodos anteriores %": "0.0",
      "Período corrente %": "92.24",
    },
    Total: {
      Descrição: "Total",
      "Despesas por pagar de períodos anteriores": "405.58",
      "Dotações corrigidas": "435374.62",
      "Cativos/Descativos": "0",
      Compromissos: "407082.0",
      Obrigações: "407082.0",
      "Períodos anteriores": "405.58",
      "Período corrente": "404706.87",
      Total: "405112.45",
      "Compromissos a transitar": "0",
      "Obrigações por pagar": "1969.55",
      "Períodos anteriores %": "0.09",
      "Período corrente %": "92.96",
    },
  },
  receita: {
    "formula de calculo": {
      Descrição: "formula de calculo",
      "Previsões Corrigidas": "(1)",
      "Receitas por Cobrar de períodos anteriores": "(2)",
      "Receitas liquidadas": "(3)",
      "Liquidações anuladas": "(4)",
      "Receitas Cobradas Brutas": "(5)",
      Emitidos: "(6)",
      Pagos: "(7)",
      "Períodos anteriores": "(8)",
      "Período corrente": "(9)",
      Total: "(10)=(5)-(7)",
      "Receita por Cobrar no Final do Ano": "(11)",
      "Períodos anteriores %": "(12)=(8)/(1)x100",
      "Período corrente %": "(13)=(9)/(1)x100",
    },
    "Receita corrente": {
      Descrição: "Receita corrente",
      "Previsões Corrigidas": "376074.62",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "367699.07",
      "Liquidações anuladas": "37.3",
      "Receitas Cobradas Brutas": "367699.07",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "367699.07",
      Total: "367699.07",
      "Receita por Cobrar no Final do Ano": "⚠️ Não cobrado (mas não registado como dívida)",
      "Períodos anteriores %": "0",
      "Período corrente %": "97.77",
    },
    R1: {
      Rubrica: "R1",
      Descrição: "Receita fiscal",
      "Previsões Corrigidas": "6715",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "6713.4",
      "Liquidações anuladas": "0",
      "Receitas Cobradas Brutas": "6713.4",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "6713.4",
      Total: "6713.4",
      "Receita por Cobrar no Final do Ano": "⚠️ Não cobrado (mas não registado como dívida)",
      "Períodos anteriores %": "0",
      "Período corrente %": "99.98",
    },
    R3: {
      Rubrica: "R3",
      Descrição: "Taxas, multas e outras penalidades",
      "Previsões Corrigidas": "18310",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "13227.46",
      "Liquidações anuladas": "37.3",
      "Receitas Cobradas Brutas": "13227.46",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "13227.46",
      Total: "13227.46",
      "Períodos anteriores %": "0",
      "Período corrente %": "72.24",
    },
    R4: {
      Rubrica: "R4",
      Descrição: "Rendimentos de propriedade",
      "Previsões Corrigidas": "31965",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "31963.18",
      "Liquidações anuladas": "0",
      "Receitas Cobradas Brutas": "31963.18",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "31963.18",
      Total: "31963.18",
      "Períodos anteriores %": "0",
      "Período corrente %": "99.99",
    },
    R5: {
      Rubrica: "R5",
      Descrição: "Transferências e subsidios correntes",
      "Previsões Corrigidas": "315884.62",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "314971.03",
      "Liquidações anuladas": "0",
      "Receitas Cobradas Brutas": "314971.03",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "314971.03",
      Total: "314971.03",
      "Períodos anteriores %": "0",
      "Período corrente %": "99.71",
    },
    R6: {
      Rubrica: "R6",
      Descrição: "Venda de bens e serviços",
      "Previsões Corrigidas": "1100",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "10",
      "Liquidações anuladas": "0",
      "Receitas Cobradas Brutas": "10",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "10",
      Total: "10",
      "Períodos anteriores %": "0",
      "Período corrente %": "0.91",
    },
    R7: {
      Rubrica: "R7",
      Descrição: "Outras receitas correntes",
      "Previsões Corrigidas": "2100",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "814",
      "Liquidações anuladas": "0",
      "Receitas Cobradas Brutas": "814",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "814",
      Total: "814",
      "Períodos anteriores %": "0",
      "Período corrente %": "38.76",
    },
    Total: {
      Rubrica: "Total",
      Descrição: "Total",
      "Previsões Corrigidas": "435374.62",
      "Receitas por Cobrar de períodos anteriores": "0",
      "Receitas liquidadas": "416949.6",
      "Liquidações anuladas": "37.3",
      "Receitas Cobradas Brutas": "416949.6",
      Emitidos: "0",
      Pagos: "0",
      "Períodos anteriores": "0",
      "Período corrente": "416949.6",
      Total: "416949.6",
      "Períodos anteriores %": "0",
      "Período corrente %": "95.77",
    },
  },
  projetos: {
    "2": {
      Objetivo: "1",
      "Nº Do Projeto": "2",
      "Designação Do Projeto": "3",
      "Rub. Or.": "4",
      "Forma de realização": "5",
      RG: "6",
      RP: "7",
      UE: "8",
      EMPR: "9",
      Início: "10",
      Fim: "11",
      "Ano Anterior": "12.0",
      "Ano t": "13",
      "Anos seguintes": "14.0",
      "Total ": "15=12+13+14",
      "Anos Anteriores": "16.0",
      "Ano t.1": "17.0",
      "Total .1": "18=16+17",
      "Nível Execução Financeira Anual (%)": "19=17/13",
      "Nível Execução Financeira Global (%)": "20=18/15",
    },
    "1 - 1": {
      Objetivo: "1.1.1",
      "Nº Do Projeto": "1 - 1",
      "Designação Do Projeto": "Administração geral - Aquisição de equipamento de informática",
      "Rub. Or.": "D6",
      "Forma de realização": "O",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2025",
      "Ano Anterior": "0.0",
      "Ano t": "500",
      "Anos seguintes": "500.0",
      "Total ": "1000",
      "Anos Anteriores": "0.0",
      "Ano t.1": "178.6",
      "Total .1": "178.6",
      "Nível Execução Financeira Anual (%)": "35,72 %",
      "Nível Execução Financeira Global (%)": "17,86 %",
    },
    "1 - 2": {
      Objetivo: "1.1.1",
      "Nº Do Projeto": "1 - 2",
      "Designação Do Projeto": "Administração geral - Aquisição de software informático",
      "Rub. Or.": "D6",
      "Forma de realização": "O",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2025",
      "Ano Anterior": "0.0",
      "Ano t": "100",
      "Anos seguintes": "500.0",
      "Total ": "600",
      "Anos Anteriores": "0.0",
      "Ano t.1": "0.0",
      "Total .1": "0",
      "Nível Execução Financeira Anual (%)": "0,00 %",
      "Nível Execução Financeira Global (%)": "0,00 %",
    },
    "1 - 3": {
      Objetivo: "1.1.1",
      "Nº Do Projeto": "1 - 3",
      "Designação Do Projeto": "Administração geral - Fotocopiadora Canon",
      "Rub. Or.": "D6",
      "Forma de realização": "O",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "31/01/2021",
      Fim: "31/01/2026",
      "Ano Anterior": "10159.8",
      "Ano t": "3600",
      "Anos seguintes": "3890.28",
      "Total ": "17650.08",
      "Anos Anteriores": "10159.8",
      "Ano t.1": "3483.36",
      "Total .1": "13643.16",
      "Nível Execução Financeira Anual (%)": "96,76 %",
      "Nível Execução Financeira Global (%)": "77,30 %",
    },
    "1 - 9": {
      Objetivo: "1.1.1",
      "Nº Do Projeto": "1 - 9",
      "Designação Do Projeto": "Administração geral - Construção de estrutura - Caixa Multibanco",
      "Rub. Or.": "D6",
      "Forma de realização": "E",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/10/2024",
      Fim: "31/12/2024",
      "Ano Anterior": "0.0",
      "Ano t": "17200",
      "Anos seguintes": "0.0",
      "Total ": "17200",
      "Anos Anteriores": "0.0",
      "Ano t.1": "13357.8",
      "Total .1": "13357.8",
      "Nível Execução Financeira Anual (%)": "77,66 %",
      "Nível Execução Financeira Global (%)": "77,66 %",
    },
    "🧮 Total por Bloco 1": {
      Objetivo: "Total:",
      "Nº Do Projeto": "1",
      "Designação Do Projeto": "🧮 Total por Bloco 1",
      "Ano Anterior": "10159.8",
      "Ano t": "61150",
      "Anos seguintes": "6390.280000000001",
      "Total ": "77700.08",
      "Anos Anteriores": "10159.8",
      "Ano t.1": "56016.66",
      "Total .1": "66176.46",
    },
    "2 - 1": {
      Objetivo: "3.3.1",
      "Nº Do Projeto": "2 - 1",
      "Designação Do Projeto": "Transportes rodoviários - Viadutos, arruamentos e obras complementares na freguesia",
      "Rub. Or.": "D6",
      "Forma de realização": "E",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2025",
      "Ano Anterior": "0.0",
      "Ano t": "4975",
      "Anos seguintes": "1000.0",
      "Total ": "5975",
      "Anos Anteriores": "0.0",
      "Ano t.1": "4915.26",
      "Total .1": "4915.26",
      "Nível Execução Financeira Anual (%)": "98,80 %",
      "Nível Execução Financeira Global (%)": "82,26 %",
    },
    "2 - 2": {
      Objetivo: "3.3.1",
      "Nº Do Projeto": "2 - 2",
      "Designação Do Projeto": "Transportes rodoviários - Requalificação de caminhos",
      "Rub. Or.": "D6",
      "Forma de realização": "E",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2025",
      "Ano Anterior": "0.0",
      "Ano t": "6450",
      "Anos seguintes": "1000.0",
      "Total ": "7450",
      "Anos Anteriores": "0.0",
      "Ano t.1": "6218.74",
      "Total .1": "6218.74",
      "Nível Execução Financeira Anual (%)": "96,41 %",
      "Nível Execução Financeira Global (%)": "83,47 %",
    },
    "2 - 3": {
      Objetivo: "3.3.1",
      "Nº Do Projeto": "2 - 3",
      "Designação Do Projeto": "Transportes rodoviários - Embelezamento da rotunda Vale do Brejo",
      "Rub. Or.": "D6",
      "Forma de realização": "O",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2024",
      "Ano Anterior": "0.0",
      "Ano t": "25",
      "Anos seguintes": "0.0",
      "Total ": "25",
      "Anos Anteriores": "0.0",
      "Ano t.1": "0.0",
      "Total .1": "0",
      "Nível Execução Financeira Anual (%)": "0,00 %",
      "Nível Execução Financeira Global (%)": "0,00 %",
    },
    "🧮 Total por Bloco 2": {
      Objetivo: "Total:",
      "Nº Do Projeto": "2",
      "Designação Do Projeto": "🧮 Total por Bloco 2",
      "Ano Anterior": "0.0",
      "Ano t": "11450",
      "Anos seguintes": "2000.0",
      "Total ": "13450",
      "Anos Anteriores": "0.0",
      "Ano t.1": "11134.0",
      "Total .1": "11134",
    },
    "3 - 1": {
      Objetivo: "2.4.5",
      "Nº Do Projeto": "3 - 1",
      "Designação Do Projeto": "Resíduos sólidos - Construção de bases para contentores",
      "Rub. Or.": "D6",
      "Forma de realização": "E",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2023",
      Fim: "31/12/2024",
      "Ano Anterior": "0.0",
      "Ano t": "100",
      "Anos seguintes": "0.0",
      "Total ": "100",
      "Anos Anteriores": "0.0",
      "Ano t.1": "0.0",
      "Total .1": "0",
      "Nível Execução Financeira Anual (%)": "0,00 %",
      "Nível Execução Financeira Global (%)": "0,00 %",
    },
    "4 - 1": {
      Objetivo: "2.4.6",
      "Nº Do Projeto": "4 - 1",
      "Designação Do Projeto":
        "Proteção do meio ambiente e conservação da natureza - Construção de casa de banho para deficientes no Parque das Malhadinhas",
      "Rub. Or.": "D6",
      "Forma de realização": "E",
      RG: "0%",
      RP: "100%",
      UE: "0%",
      EMPR: "0%",
      Início: "01/01/2024",
      Fim: "31/12/2024",
      "Ano Anterior": "0.0",
      "Ano t": "100",
      "Anos seguintes": "0.0",
      "Total ": "100",
      "Anos Anteriores": "0.0",
      "Ano t.1": "0.0",
      "Total .1": "0",
      "Nível Execução Financeira Anual (%)": "0,00 %",
      "Nível Execução Financeira Global (%)": "0,00 %",
    },
    "🧮 Total por Bloco 3": {
      Objetivo: "Total:",
      "Nº Do Projeto": "3",
      "Designação Do Projeto": "🧮 Total por Bloco 3",
      "Ano Anterior": "10159.8",
      "Ano t": "72800",
      "Anos seguintes": "8390.28",
      "Total ": "91350.08",
      "Anos Anteriores": "10159.8",
      "Ano t.1": "67150.66",
      "Total .1": "77310.46",
    },
  },
  tesouraria: {
    "Caixa - Cheque": {
      Referência: "Caixa - Cheque",
      "Saldo Dia Anterior": "0.0",
      Entrada: "172.98",
      Soma: "172.98",
      Saída: "172.98",
      "Saldo Dia Seguinte": "0.0",
    },
    "Caixa - Interno": {
      Referência: "Caixa - Interno",
      "Saldo Dia Anterior": "0.0",
      Entrada: "99.68",
      Soma: "99.68",
      Saída: "0.0",
      "Saldo Dia Seguinte": "99.68",
    },
    "Caixa - Numerário": {
      Referência: "Caixa - Numerário",
      "Saldo Dia Anterior": "0.0",
      Entrada: "20714.23",
      Soma: "20714.23",
      Saída: "20387.06",
      "Saldo Dia Seguinte": "327.17",
    },
    "Subtotal - Caixa": {
      Referência: "Subtotal - Caixa",
      "Saldo Dia Anterior": "0.0",
      Entrada: "20986.89",
      Soma: "20986.89",
      Saída: "20560.04",
      "Saldo Dia Seguinte": "426.85",
    },
    "CGD - Transferência": {
      Referência: "CGD - Transferência",
      "Saldo Dia Anterior": "0.0",
      Entrada: "9929.11",
      Soma: "9929.11",
      Saída: "82112.3",
      "Saldo Dia Seguinte": "-72183.19",
    },
    "CGD - Interno": {
      Referência: "CGD - Interno",
      "Saldo Dia Anterior": "0.0",
      Entrada: "72183.19",
      Soma: "72183.19",
      Saída: "0.0",
      "Saldo Dia Seguinte": "72183.19",
    },
    "Subtotal - CGD": {
      Referência: "Subtotal - CGD",
      "Saldo Dia Anterior": "0.0",
      Entrada: "82112.3",
      Soma: "82112.3",
      Saída: "82112.3",
      "Saldo Dia Seguinte": "0.0",
    },
    "CA - Interno": {
      Referência: "CA - Interno",
      "Saldo Dia Anterior": "0.0",
      Entrada: "35751.53",
      Soma: "35751.53",
      Saída: "0.0",
      "Saldo Dia Seguinte": "35751.53",
    },
    "CA - Numerário": {
      Referência: "CA - Numerário",
      "Saldo Dia Anterior": "0.0",
      Entrada: "15075.12",
      Soma: "15075.12",
      Saída: "0.0",
      "Saldo Dia Seguinte": "15075.12",
    },
    "CA - Cartão Multibanco": {
      Referência: "CA - Cartão Multibanco",
      "Saldo Dia Anterior": "0.0",
      Entrada: "0.0",
      Soma: "0.0",
      Saída: "1216.25",
      "Saldo Dia Seguinte": "-1216.25",
    },
    "CA - Transferência": {
      Referência: "CA - Transferência",
      "Saldo Dia Anterior": "0.0",
      Entrada: "400363.22",
      Soma: "400363.22",
      Saída: "379901.9",
      "Saldo Dia Seguinte": "20461.32",
    },
    "Subtotal - CA": {
      Referência: "Subtotal - CA",
      "Saldo Dia Anterior": "0.0",
      Entrada: "451362.85",
      Soma: "451362.85",
      Saída: "381118.15",
      "Saldo Dia Seguinte": "70244.7",
    },
    "Movimentos Tesouraria": {
      Referência: "Movimentos Tesouraria",
      "Saldo Dia Anterior": "0.00",
      Entrada: "554462.04",
      Soma: "554462.04",
      Saída: "483790.49",
      "Saldo Dia Seguinte": "70671.55",
    },
    "Total Período": {
      Referência: "Total Período",
      Entrada: "554462.04",
      Saída: "483790.49",
      "Saldo Dia Seguinte": "70671.55",
    },
  },
}
